parafoil_simulator:
  ros__parameters:
    initial_position: [0.0, 0.0, -70.0]
    initial_velocity: [4.5, 0.0, 0.9]
    wind:
      enable_steady: true
      enable_gust: false
      enable_colored: false
      steady_wind: [0.0, 6.0, 0.0]
